modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]

modId="jobs"
version="1.1"
displayName="HoloTabi-Jobs"
credits=""
authors="PolarFox27, MasterTDF"
description='''
A mod that adds a Jobs system to Minecraft, with Rewards and Crafts Unlocking.
'''
